"""Утилиты для метаданных .docx.

new_document() возвращает Document с очищенными core_properties,
чтобы Word не показывал дефолты python-docx в File > Properties.
"""

from docx import Document


def new_document():
    """Создать Document и очистить служебные метаданные.

    python-docx по умолчанию проставляет Author='python-docx' и
    Comments='generated by python-docx'. Здесь оба поля (и смежные)
    принудительно обнуляются - вызывать вместо Document().
    """
    doc = Document()
    cp = doc.core_properties
    cp.author = ""
    cp.last_modified_by = ""
    cp.comments = ""
    cp.title = ""
    cp.subject = ""
    cp.keywords = ""
    cp.category = ""
    return doc
